# Site
repository: govindbhardwaj/govindbhardwaj.github.io
favicon: images/favicon.ico

# Personal info
name: Govind Bhardwaj
title: Full-Stack DevOps
email: govindbhardwaj@outlook.com
website: https://govindbhardwaj.github.io

# Social links
twitter_username: kumargovind88
github_username:  govindbhardwaj
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: govindbhardwaj
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Govind and I'm a full-stack developer and orchestration engineer. As well as developing and orchestrating softwares I also have experience making software and web apps secure. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> <mark>Docker</mark> <mark>Jenkins</mark> <mark>Java</mark> <mark>Springboot</mark> and <mark>JHipster</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Guitar and Flute Playing
   - Blogging
   - Gardening
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: govindbhardwaj/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
